CarambolaBundle_homepage:
    pattern:  /
    defaults: { _controller: CarambolaBundle:Page:index }
    requirements:
        _method:  GET

CarambolaBundle_car_show:
    pattern:  /{id}
    defaults: { _controller: CarambolaBundle:Car:show }
    requirements:
        _method:  GET
        id: \d+

CarambolaBundle_rental_reserve:
    pattern:  /reserve/{car_id}
    defaults: { _controller: CarambolaBundle:Rental:reserve}
    requirements:
        _method:  POST
        car_id: \d+