<?php

namespace CarambolaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalRepository extends EntityRepository
{
    public function getRental($carId)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.car = :car_id')
            ->setParameter('car_id', $carId);

        return $qb->getQuery()
            ->getResult();
    }
}
